config {
    type: "incremental",
    uniqueKey: ["appID"],
    schema: "stg",
    dependencies: ["first_table"],
    bigquery: {
      partitionBy: "app_id"
    }
}



CREATE TABLE IF NOT EXISTS stg.second_table AS
  SELECT *
  FROM ${ref("first_table")};

CREATE OR REPLACE TABLE stg.second_table AS
  SELECT *
  FROM ${ref("first_table")}
  ${ when(incremental(), `WHERE date > (SELECT IFNULL(MAX(date),'2000-01-01') FROM ${self()})`)}






