config {
    type: "table",
    bigquery: {
      columns: {
        appID: "", appName: "", SpType: "", signature: "", platform: "", identity: "", date: ""
      },
        partitionBy: "DATE(event_timestamp)",
        clusterBy: ["appID"]
    }
}

pre_operations {
  DECLARE event_timestamp DATE;
  SET event_timestamp  =  (
    ${when(incremental(),
    `SELECT max(date) FROM ${self()}`,
    `SELECT DATE("2023-08-01")`)}
  )
}

SELECT appID, appName, SpType, signature, platform, identity, date
FROM `data-processing-272107.dataform.first_table`
WHERE date = event_timestamp
